<?php

/**
 * @file
 *  Provides an annotation plugin to point content per x-y on html elements.
 */


/**
 * Implementation of hook_annotation_info().
 */
function annotation_point_annotation_info($type) {
  if ($type == 'annotation') {
    return array(
      'point' => array(
        'title' => t('Point'),
        'view' => 'annotation_point_view',
      ),
    );
  }
}


/**
 * View function for annotation_view().
 *
 * Show a marker for annotation api.
 */
function annotation_point_view($annotation, $content) {
  list($container, $posx, $posy, $width, $height, $cwidth, $cheight) = explode('|', $annotation->vars);
  $output = '<div class="annotation-point" rel="'. $annotation->vars .'"><div class="content">'. $content .'</div></div>';
  drupal_add_css(drupal_get_path('module','annotation_point'). '/annotation_point.css', 'module');
  drupal_add_js(drupal_get_path('module','annotation_point'). '/annotation_point.js', 'module');
  return $output;
}

/**
 *
 */
function annotation_point_form_annotation_form_alter(&$form, $form_state) {
  if ($form['#annotation']->type == 'point') {
    $form['dragger'] = array('#value' => '<div class="dragger"></div>');
    $form['#attributes']['class'] .= ' annotation-point-form';
    $form['vars']['#attributes']['class'] .= ' annotation-point-vars';
    //$form['vars']['#type'] = 'textfield';
    drupal_add_css(drupal_get_path('module','annotation_point'). '/annotation_point.css', 'module');
    jquery_ui_add(array('ui.draggable'));
    drupal_add_js(drupal_get_path('module','annotation_point'). '/annotation_point_form.js', 'module');
    //dpm($form);
  }
}