<?php

/**
 * @file
 *  example implemantion for stats.module
 */

/**
 * Return some stats info types
 */
function stats_example_stats_info() {
  $return = array();

  $return['example_user_nodecount'] = array(
    'handler' => 'stats_default_worker', // Default
    'callback storage' => 'stats_callback_default_storage', // Default for handler
    'callback calculation' => 'stats_callback_default_calculation', // Default for handler
    //'callback stroing calcualtion' => --- @TODO!
    'callback views data' => 'stats_callback_default_views_data_implementation', // Default for handler
    'callback views data alter' => 'stats_callback_default_views_data_alter_implementation', // Default for handler
    'calculation mode' => 'COUNT', // Default for handler
    /// General
    'type' => 'user_nodecount',
    'active' => TRUE,
    'name' => t('User - Node count'),
    'description' => t('Counts the number of nodes created by a user'),
    // Source
    'source table' => 'node',
    'source subject field' => 'uid',
    'source value field' => 'nid',
    // Subject - needed for views
    'subject table' => 'users',
    'subject field' => 'uid',
    // Storage
    'storage table' => 'stats_example',
    'storage subject field' => 'subject',
    'storage value field' => 'value',
    'storage type field' => 'type',

    // @TODO: Views implementation
    //'views table declared' => FALSE, // FALSE default, TRUE for allready declared as table for views
    //'views field declared' => FALSE, // FALSE default,
    'storage views fields' => array(
      'value' => 'numeric',
      'type' => 'string',
    ),
    'storage views relations' => array(
      //'subject' => 'users',
      'subject' => array('table' => 'users', 'field' => 'uid'),
    ),

  );
  return $return;
}

/**
 * Implementation of hook_nodeapi().
 */
function stats_example_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

  switch ($op) {
    case 'insert':
    case 'update':
      // Update stats for the author
      stats_run('example_user_nodecount', $node->uid);
      break;
  }

}
