<?php

/**
 * @file
 *  Provides an annotation plugin to point content per x-y on html elements.
 */


/**
 * Implementation of hook_annotation_info().
 */
function annotation_point_annotation_info() {
  return array(
    'annotation' => array(
      'point' => array(
        'title' => t('Point'),
        'view' => 'annotation_point_view',
      ),
    ),
  );
}


/**
 * View function for annotation_view().
 *
 * Show a marker for annotation api.
 */
function annotation_point_view($annotation, $content) {
  list($container, $posx, $posy, $width, $height, $cwidth, $cheight) = explode('|', $annotation->vars);
  $output = '<div class="annotation-point" rel="'. $annotation->vars .'"><div class="content">'. $content .'</div></div>';

/**
  TO COME: more generic behaviour with settings array
  $settings = array(
    'aid' => $annotation->aid,
    'container' => $container,
    'posx' => $posx,
    'posy' => $posy,
  ) + (array) $annotation;
  drupal_add_js(array('annotation_point' => array($annotation->aid => $settings)), 'setting');
*/

  // Leave old behaviour at the momen
  //$output = "<div id=\"annotation-point-$annotation->aid\" class=\"annotation-point\"><div class=\"content\">$content</div></div>";

  drupal_add_css(drupal_get_path('module','annotation_point'). '/annotation_point.css', 'module');
  drupal_add_js(drupal_get_path('module','annotation_point'). '/annotation_point.js', 'module');
  return $output;
}

/**
 *
 */
function annotation_point_form_annotation_form_alter(&$form, $form_state) {
  if ($form['#annotation']->type == 'point') {
    $form['dragger'] = array('#value' => '<div class="dragger"></div>', '#weight' => -998);
    $form['adder'] = array('#value' => '<div class="adder" rel="'. t('Hide') .'"><a>'. t('Add') .'</a></div>', '#weight' => -998);
    $form['#attributes']['class'] .= ' annotation-point-form';
    $form['vars']['#attributes']['class'] .= ' annotation-point-vars';
    //$form['vars']['#type'] = 'textfield';
    drupal_add_css(drupal_get_path('module','annotation_point'). '/annotation_point.css', 'module');
    jquery_ui_add(array('ui.draggable'));
    drupal_add_js(drupal_get_path('module','annotation_point'). '/annotation_point_form.js', 'module');
  }
}