<?php

/**
 * @file
 *   Queue implemenatation for stats calls
 */

/**
 * Queues the creation of stats runs.
 *
 * Functionality is driven by drupal_queue.module.
 * @param $type
 * @param $subjects
 *  - array of subjects or single non-array subject
 * @param $additions
 *  - array of additions arrays or single non-array addition
 *    or additions array if subject is single non-array addition
 * @return
 */
function stats_queue($type, $subjects = NULL, $additions = NULL, $delete_unnecessary = TRUE) {

  // Queue to recalculate all
  if (!isset($subjects)) {
    // delete all subject recalcualtion
    if ($delete_unnecessary) {
      $query = "DELETE FROM {stats_queue} WHERE type = '%s'";
      db_query($query, $type);
    }
    $write = (object) array(
      'type' => $type,
      'subject' => NULL,
      'addition' => NULL,
    );
    drupal_write_record('stats_queue', $write);
  }
  // Queue to calculate specific subjects
  else {

    // Transform subject to array
    if (!is_array($subjects)) {
      $subjects = array($subjects);
    }
    $subjects = array_values($subjects);

    // Single addition will be applied to each subject
    // transform to array(array())
    if (isset($additions) && !is_array($additions)) {
      $additions = array_fill(0, count($subjects), array($additions));
    }

    $recalculate = array();
    $add = array();
    if (!isset($additions)) {
      $recalculate = $subjects;
      $add = array();
    }
    else {
      $ca = count($additions);
      $add = array_slice($subjects, 0, $ca, TRUE);
      $recalculate = array_slice($subjects, $ca);
    }

    // Add addition subjects
    if (count($add)) {
      foreach ($add as $i => $a) {
        $addition = $additions[$i];
        // Addition has to be an array
        if (!is_array($addition)) $addition = array($addition);
        $write = (object) array(
          'type' => $type,
          'subject' => $a,
          'addition' => $addition,
        );
        drupal_write_record('stats_queue', $write);
      }
    }

    // Add subjects for recalcualtion
    if (count($recalculate)) {
      // Delete existing
      $args = array($type);
      $casts = array();
      $writes = array();
      foreach ($recalculate as $rec) {
        $args[] = serialize($rec);
        $casts[] = "'%s'";
        $writes[] = array(
          'type' => $type,
          'subject' => $rec,
          'addition' => NULL,
        );
      }
      // delete all subject addition recalculation
      if ($delete_unnecessary) {
        $query = "DELETE FROM {stats_queue} WHERE type = '%s' AND subject IN (". implode(',', $casts) .")";
        db_query($query, $args);
      }
      foreach ($writes as $write) {
        drupal_write_record('stats_queue', $write);
      }
    }
  }

  // Activate queue for type
  $queue = drupal_queue_get('stats');
  return $queue->createItem($type);
}

/**
 * Implementation of hook_cron_queue_info().
 */
function stats_queue_cron_queue_info() {
  $queues['stats'] = array(
    'worker callback' => 'stats_queue_worker_callback',
    'time' => 60,
  );
  return $queues;
}

/**
 * Runs all items of a specifix stats type.
 */
function stats_queue_worker_callback($type) {

  // Load all data to process from stats_queue, then delete it
  $query = "SELECT * FROM {stats_queue} WHERE type = '%s'";
  $res = db_query($query, $type);
  $items = array();
  $recalculate_all = FALSE;
  $recalc = array();
  $adds = array();
  while ($obj = db_fetch_object($res)){
    $subject = (isset($obj->subject)) ? unserialize($obj->subject) : NULL;
    $addition = (isset($obj->addition)) ? unserialize($obj->addition) : NULL;
    if (!isset($subject)) {
      $recalculate_all = TRUE;
      break;
    }
    elseif (!isset($addition)) {
      $recalc[] = $subject;
    }
    else {
      $adds[] = (object) array('subject' => $subject, 'addition' => $addition);
    }
  }

  // DELETE all of type
  db_query("DELETE FROM {stats_queue} WHERE type ='%s'", $type);

  $worker = stats_get_worker($type);

  if ($recalculate_all) {
    $worker->add_all();
  }
  else {
    foreach ($recalc as $rec) {
      $worker->add_subject($rec);
    }
    foreach ($adds as $add) {
      $worker->add_subject($add->subject, $add->addition);
    }
  }

  return $worker->execute();
}